name: Semgrep Check Run

on:
  pull_request:

jobs:
  write_variable_to_file:
    runs-on: ubuntu-latest

    steps:
      - name: Write variable to file
        env:
          MY_VARIABLE: "Hello, world!"
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" > my_output_file.txt

      - name: Display contents of the file
        run: |
          cat my_output_file.txt
          
